### ISSUE TITLE
Prefixes for bad wdl's for validate, run or both

### ISSUE THREAD

**Issue by sckott** [FredHutch/wdl-unit-tests#59]
via @tefirman in https://github.com/FredHutch/wdl-unit-tests/issues/53#issuecomment-2581443125

My proposal is thus for prefixes:

- should fail womtool, but not cromwell run: `badVal`
- should not fail womtool, but should fail cromwell run: `badRun`
- should fail womtool, and should fail cromwell run: `badValRun`
- should not fail womtool or cromwell run: no prefix

Another different take on this is to nest similar types of wdls within the same dir, and then we know the expectation from the parent dir the wdl's are in. e.g., 

- good
  - helloHostname
  - helloDockerHostname
  - etc
- badVal
  - testWdl
- badRun
  - someWdl
- badValRun
  - badFile

A 3rd option that I kinda like is maintaining the metadata about the various WDLs in a single file, json or yaml, whatever. e.g., 

```yaml
wdls:
  badFile: 
    - womtool: fail
    - cromwell_run: succeed
  helloHostname: 
    - womtool: succeed
    - cromwell_run: succeed
  parseBatchfile: 
    - womtool: succeed
    - cromwell_run: fail
```
