### ISSUE TITLE
[Quick] tweak gha for womtools and cromwell

### ISSUE THREAD

**Issue by seankross** [FredHutch/wdl-unit-tests#88]
Can I add this to the gh actions for womtools and cromwell? This will make the badges in the readme make more sense.

```yaml
on:
  push:
    branches:
      - main
```
